[build]
target = "i686-pc-windows-msvc"

[target.i686-pc-windows-msvc]
rustflags = [
    "-C", "linker=crinkler",
    "-C", "link-args=/COMPMODE:INSTANT /SUBSYSTEM:CONSOLE /HASHSIZE:100 /REPLACEDLL:kernel32=KernelBase /FALLBACKDLL:KernelBase=kernel32 user32.lib libucrt.lib libvcruntime.lib"
]

[unstable]
build-std = ["core", "alloc", "std", "compiler_builtins", "panic_abort"]
build-std-features = ["compiler-builtins-mem", "panic_immediate_abort"]
