[build]
target = "i686-pc-windows-msvc"

[target.i686-pc-windows-msvc]
rustflags = [
    "-C", "linker=crinkler",
    "-C", "link-args=/UNALIGNCODE /TRANSFORM:CALLS /ORDERTRIES:50 kernel32.lib user32.lib libucrt.lib libvcruntime.lib"
]

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "link-args=user32.lib libucrt.lib libvcruntime.lib"
]

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
